---
- name: enable and restart vpn services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  async: 1
  poll: 0
  loop: "{{ __vpn_services }}"

- name: Wait for ssh connection to return
  wait_for_connection:
    delay: 3
    timeout: 300
